server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaultdb
    username: vaultuser
    password: vaultpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-very-long-secret-key-which-should-be-at-least-256-bits-long-for-security}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    displayRequestDuration: true
    filter: true
    showExtensions: true
    showCommonExtensions: true
    tryItOutEnabled: true
  show-actuator: false
  group-configs:
    - group: 'management-server-api'
      display-name: 'Management Server API'
      paths-to-match: '/api/**'