version: '3.8'

services:
  attacker:
    build: .
    volumes:
      - ./attacks:/app/attacks
      - ./menu:/app/menu
      - ./utils:/app/utils
      - ./metrics:/app/metrics
      - ./graphs:/app/graphs
    environment:
      - TARGET_HOST=host.docker.internal
      - TARGET_PORT=8080
      - TARGET_URL=http://host.docker.internal:8080
    stdin_open: true
    tty: true
    networks:
      - ddos-network

networks:
  ddos-network:
    driver: bridge 